### ISSUE TITLE
Project Goals and Requirements

### ISSUE THREAD

**Issue by batflyer** [starling-lab/Textual_Annotation_Interface#4]
Copies of the jar files from BoostSRL are currently present here. Instead of requiring that this automatically runs learning/inference, the goal of this repository should be something fairly self-contained.

For example: if the main goal of this project is "distinguish positive examples by highlighting sentences to create data sets", the output should be positives, negatives, and facts. It can then be up the the user what they wish to do with the created data set(s).

**Comment by Abhiramon** [comment]
The positive, negative and facts can be obtained in the "train" directory when the program ends or is stopped after training is completed. Can you please elaborate on the requirements? Should I break-down the python code into modules?

**Comment by Abhiramon** [comment]
I think we can stick to using BoostSRL for now and add other models later on. I'll close this issue.
