### ISSUE TITLE
OS Interaction

### ISSUE THREAD

**Issue by hayesall** [starling-lab/Textual_Annotation_Interface#7]
Bash generally isn't available on Windows by default. If a goal is for this to work on both Windows and a Linux/OSX machine, we should remedy this in one of two ways:

1. Remove requirement altogether by re-writing the shell scripts to Python equivalents.
2. Explicitly require bash-for-Windows or Git Bash (or something similar).

**Comment by batflyer** [comment]
The latest version seems to be working correctly on Fedora. @Abhiramon Are you developing on a Windows machine still?
